# Generated by Django 4.0.5 on 2022-08-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Gender', models.CharField(default=None, max_length=12)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Mob', models.CharField(default=None, max_length=13)),
                ('Email', models.EmailField(default=None, max_length=100)),
                ('Institution', models.CharField(default=None, max_length=100)),
                ('University', models.CharField(default=None, max_length=100)),
                ('Dob', models.DateField(default=None)),
                ('Phd_Reg', models.IntegerField(default=None)),
                ('Phd_Joining_Date', models.DateField(default=None)),
                ('Research_Topic', models.CharField(default=None, max_length=100)),
                ('Research_Guide', models.CharField(default=None, max_length=100)),
                ('Guide_Mail', models.EmailField(default=None, max_length=100, null=True)),
                ('Guide_Phone', models.CharField(default=None, max_length=13, null=True)),
                ('Guide_Dpt', models.CharField(default=None, max_length=100)),
                ('Co_Guide', models.BooleanField(blank=True, default=None, null=True)),
                ('Co_Guide_Name', models.CharField(default=None, max_length=100, null=True)),
                ('Co_Guide_Mail', models.EmailField(default=None, max_length=100, null=True)),
                ('Co_Guide_Phone', models.CharField(default=None, max_length=13, null=True)),
                ('Co_Guide_Dpt', models.CharField(default=None, max_length=100, null=True)),
                ('Eligibility', models.BooleanField(blank=True, default=None, null=True)),
                ('Reject', models.BooleanField(blank=True, default=False, null=True)),
                ('Cusatian', models.BooleanField(blank=True, default=None, null=True)),
                ('Cusat_Id', models.FileField(blank=True, default=None, null=True, upload_to='files')),
                ('Short_Name', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_Name', models.CharField(default=None, max_length=100, null=True)),
                ('Month', models.CharField(default=None, max_length=100)),
                ('Year', models.IntegerField(default=None)),
                ('CommenceDate', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('Register_Number', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('RegNumber', models.IntegerField(blank=True, default=None, null=True)),
                ('UserId', models.IntegerField(blank=True, default=None, null=True)),
                ('Photo', models.ImageField(upload_to='pics')),
                ('Achievements', models.TextField()),
                ('Marks', models.IntegerField(blank=True, default=None, null=True)),
                ('Attendance', models.IntegerField(blank=True, default=None, null=True)),
                ('Dropout', models.BooleanField(blank=True, default=False, null=True)),
                ('ApplicationId', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='owner.applicants')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentName', models.CharField(default=None, max_length=100)),
                ('FreeForCusat', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(default=None, max_length=100)),
                ('TotalHour', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentStatus', models.BooleanField(blank=True, default=None, null=True)),
                ('PaymentDetails', models.FileField(blank=True, default=None, null=True, upload_to='files')),
                ('PaymentId', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='owner.payments')),
                ('StudentId', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='owner.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(default=None, max_length=100, null=True)),
                ('StudentReg', models.IntegerField(blank=True, default=None, null=True)),
                ('Attendance', models.IntegerField(default=None)),
                ('AttendancePercentage', models.IntegerField(blank=True, default=None, null=True)),
                ('AttendanceMark', models.IntegerField(blank=True, default=None, null=True)),
                ('Assignment1Mark', models.IntegerField(default=None)),
                ('Assignment2Mark', models.IntegerField(default=None)),
                ('TotalAssignmentMark', models.IntegerField(blank=True, default=None, null=True)),
                ('GdMark', models.IntegerField(default=None)),
                ('CpMark', models.IntegerField(default=None)),
                ('Total', models.IntegerField(blank=True, default=None, null=True)),
                ('ExternalMark', models.IntegerField(blank=True, default=0, null=True)),
                ('StudentId', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='owner.candidates')),
            ],
        ),
        migrations.AddField(
            model_name='applicants',
            name='Batch',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='owner.batches'),
        ),
    ]
