# Generated by Django 4.0.5 on 2022-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Age', models.IntegerField(default=None)),
                ('Gender', models.CharField(default=None, max_length=12)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Email', models.EmailField(default=None, max_length=100)),
                ('Department', models.CharField(default=None, max_length=100)),
                ('Eligibility', models.BooleanField(default=False)),
            ],
        ),
    ]
