# Generated by Django 4.0.5 on 2022-06-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='Eligibility',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=100)),
                ('Photo', models.ImageField(upload_to='pics')),
                ('Achievements', models.TextField()),
                ('PaymentStatus', models.BooleanField(default=False)),
                ('Marks', models.IntegerField(blank=True, default=None, null=True)),
                ('Attendance', models.IntegerField(blank=True, default=None, null=True)),
                ('ApplicationId', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='owner.applicants')),
            ],
        ),
    ]
