# Generated by Django 4.0.5 on 2022-06-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_subjects_alter_candidates_paymentstatus_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='PaymentDetails',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files'),
        ),
    ]
