# Generated by Django 4.0.5 on 2022-06-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_candidates_paymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='id',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='SubjectId',
        ),
        migrations.AddField(
            model_name='applicants',
            name='Subject',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='candidates',
            name='RegNumber',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='Register_Number',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='candidates',
            name='SubjectId',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='owner.subjects'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='Year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='UserId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
