# Generated by Django 4.0.5 on 2022-06-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_remove_candidates_id_remove_marks_subjectid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentName', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='PaymentDetails',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='PaymentStatus',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='Year',
        ),
        migrations.CreateModel(
            name='UserPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentStatus', models.BooleanField(blank=True, default=None, null=True)),
                ('PaymentDetails', models.FileField(blank=True, default=None, null=True, upload_to='files')),
                ('PaymentId', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='owner.payments')),
                ('StudentId', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='owner.candidates')),
            ],
        ),
    ]
